[project]
name = "rl-gridworld-16"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.1",
    "pyqt6>=6.10.2",
    "torch>=2.9.1",
]
